

CREATE DATABASE [Test] CONTAINMENT = NONE  
ON PRIMARY (NAME = N'Test_1', FILENAME = N'E:\MSSQL\Data\Test_1.mdf', SIZE=36GB, MAXSIZE=UNLIMITED, FILEGROWTH = 1GB )
LOG ON (NAME = N'Test_log',   FILENAME = N'E:\MSSQL\Data\Test_log.ldf', SIZE=2GB, MAXSIZE=20GB, FILEGROWTH=1GB )
GO


--ALTER DATABASE [Test] MODIFY FILE ( NAME = N'Test_1', SIZE = 36GB )
