/*
SELECT * FROM dbo.vDbPtSt WHERE [table] LIKE 'B%' ORDER BY [table]
exec sp_helpindex2 'B%'
exec sp_spaceused2 @objname='A%', @Ord=1
exec sp_spaceused2 @objname='B%', @Ord=1
exec sp_configure 'max server memory (MB)'
exec sp_configure 'cost threshold for parallelism'
exec sp_configure 'max degree of parallelism'
exec sp_configure
*/
/*
cost threshold for parallelism
max degree of parallelism
*/
/*
SELECT * FROM dbo.zTest
--WHERE Loop1 = 0

SELECT Tabl, Cardin, Rang, Cardin*Rang RowCt, Loop1 
FROM dbo.zTest WHERE Tabl <> 'A0' --AND Cardin >= 14336
ORDER BY Cardin 
SELECT CONCAT('B',SUBSTRING(Tabl,2,LEN(Tabl)-1)), Cardin, Rang, Cardin*Rang RowCt 
FROM dbo.zTest WHERE Tabl <> 'A0' ORDER BY Cardin 
*/
/*
*/
/*
SELECT [name], index_id, COUNT(*) FROM dbo.vOsBuf  WHERE object_id > 1000  GROUP BY [name], index_id ORDER BY index_id, [name]
DECLARE @tOsBuf TABLE([name] varchar(250), index_id int, ct int) --CREATE TABLE #tOsBuf ([name] nvarchar(250), index_id int, ct int)
INSERT @tOsBuf SELECT [name], index_id, COUNT(*) ct  FROM dbo.vOsBuf WHERE object_id > 1000 AND index_id = 1 GROUP BY [name], index_id
--DELETE @tOsBuf WHERE ([name] NOT LIKE 'A%' AND [name] NOT LIKE 'B%') --SELECT * FROM @tOsBuf --AND ([name] LIKE 'A%' OR [name] LIKE 'B%') AND [name] <> 'A' AND [name] <> 'B'
*/
/*
*/
-- SELECT @s = CONCAT('SELECT MAX(b.TI), COUNT(*) FROM dbo.',@tabl,CASE LEN(@Tabl) WHEN 3 THEN '' ELSE ' ' END,' a INNER LOOP JOIN dbo.A b ON b.AID = a.AID  ') 
-- WHERE a.GID = 1 OPTION(MAXDOP 1) --PRINT @s 
USE Test
GO
DECLARE @Ts int; SELECT @Ts = 8*SUM(irp)/1024 FROM dbo.vtest WHERE ([table] LIKE 'A%' OR [table] LIKE 'B%') AND [table] <> 'A' AND [table] <> 'B'
SELECT @Ts Tabls, * FROM sys.configurations WHERE name = 'max server memory (MB)'
SET NOCOUNT ON -- load tables into memory
DECLARE @tOsBuf TABLE(cd int, [name] varchar(250), index_id int, ct int) -- CREATE TABLE #tOsBuf (cd int, [name] nvarchar(250), index_id int, ct int)
INSERT @tOsBuf SELECT 1 cd, [name], index_id, COUNT(*) ct FROM dbo.vOsBuf WHERE object_id > 1000 AND index_id = 1 GROUP BY [name], index_id HAVING ([name] LIKE 'A%' OR [name] LIKE 'B%') ORDER BY index_id, [name] --DELETE @tOsBuf WHERE ([name] NOT LIKE 'A%' AND [name] NOT LIKE 'B%') 
DECLARE @Tx TABLE(Tabl nvarchar(250), Cardin int, Rang int, ird int, ct int, ct2 int)
INSERT @Tx  SELECT z.Tabl, z.Cardin, z.Rang, z.ird, ISNULL(a.ct,0), ISNULL(b.ct,0)
FROM dbo.zTest z LEFT JOIN @tOsBuf a ON a.[name] = z.Tabl LEFT JOIN @tOsBuf b ON b.[name] = CONCAT('B',SUBSTRING(z.Tabl,2,LEN(z.Tabl)-1)) --  WHERE ISNULL(ct,0) < z.ird --ORDER BY z.Tabl -- index_id, [name] --SELECT * FROM @Tx

DECLARE @tabl nvarchar(250), @tabk nvarchar(250), @Card int, @Rg int, @Rw int, @s nvarchar(4000), @s2 nvarchar(1000), @sp nvarchar(1), @R1 int, @R2 int, @sa nchar(2)='--', @sb nchar(2)=', '
IF EXISTS(SELECT * FROM @Tx WHERE Tabl = 'A' AND ct < ird)
BEGIN
 SELECT @R1=MAX(b.TI), @R2=COUNT(*) FROM dbo.AJ a INNER LOOP JOIN dbo.A b ON b.AID = a.AID 
 SELECT @R1=MAX(b.TI), @R2=COUNT(*) FROM dbo.A a INNER JOIN dbo.AI b ON b.AID = a.AID 
 SELECT @R1=MAX(b.TI), @R2=COUNT(*) FROM dbo.A a INNER LOOP JOIN dbo.A1 b ON b.GID = a.GID AND b.[SID] = a.[SID]
END --SELECT * FROM @Tx
DECLARE @T TABLE(ID int IDENTITY, Tabl nvarchar(250), Tabk nvarchar(250), Cardin int PRIMARY KEY, Rang int, RowCt int, Loop1 int)
INSERT @T SELECT Tabl, CONCAT('B',SUBSTRING(Tabl,2,LEN(Tabl)-1)), Cardin, Rang, Cardin*Rang RowCt, 0 Loop1 
FROM @Tx WHERE Tabl <> 'A' AND (ct < ird OR ct2 < ird) ORDER BY Cardin  --SELECT * FROM @T 
DECLARE c CURSOR FOR SELECT Tabl, Tabk, Cardin, Rang, RowCt FROM @T ORDER BY Cardin
OPEN c
FETCH NEXT FROM c INTO @tabl, @tabk, @Card, @Rg, @Rw
WHILE @@FETCH_STATUS = 0
BEGIN 
 SELECT @sp = CASE LEN(@Tabl) WHEN 3 THEN '' ELSE ' ' END 
 SELECT @s = CONCAT('SELECT @R1=MAX(b.TI), @R2=COUNT(*) FROM dbo.',@tabl,CASE LEN(@Tabl) WHEN 3 THEN '' ELSE ' ' END
 ,' a INNER LOOP JOIN dbo.',@tabk,CASE LEN(@Tabl) WHEN 3 THEN '' ELSE ' ' END,' b ON b.GID = a.GID AND b.SID = a.SID 
PRINT CONCAT(@sa,CONVERT(char(23),GETDATE(),121),@sb,@tabl,@sp,@sb,STR(@Card,6),STR(@RG,7),@sb,@Rw,@R1,@sb,@R2) ') 
 exec sp_executesql @s, N'@tabl nvarchar(250), @Card int, @Rg int, @Rw int, @R1 int, @R2 int, @sa nchar(2), @sb nchar(2), @sp nvarchar(1)', @tabl, @Card, @RG, @Rw, @R1, @R2, @sa, @sb,@sp
 FETCH NEXT FROM c INTO @tabl, @tabk, @Card, @Rg, @Rw
END
CLOSE c
DEALLOCATE c --DROP TABLE IF EXISTS #tOsBuf
INSERT @tOsBuf SELECT 2 cd, [name], index_id, COUNT(*) ct FROM dbo.vOsBuf WHERE object_id > 1000 AND index_id = 1 GROUP BY [name], index_id HAVING ([name] LIKE 'A%' OR [name] LIKE 'B%') ORDER BY index_id, [name]
;WITH t AS ( SELECT cd, [name], ct, SUBSTRING([name],1,1) n1, SUBSTRING([name],2,LEN([name])-1) n2 FROM @tOsBuf  )
SELECT a2.cd, a2.[name] Tabl, a2.ct act2, b2.[name] TabB, b2.ct bct2, a1.ct act1, b1.ct bct1, y1.user_seeks, y1.user_scans, y2.user_seeks, y2.user_scans
FROM t a2 LEFT JOIN t b2 ON b2.cd = 2 AND b2.n1 = 'B' AND b2.n2 = a2.n2 LEFT JOIN t a1 ON a1.cd = 1 AND a1.n1 = 'A' AND a1.n2 = a2.n2
		  LEFT JOIN t b1 ON b1.cd = 1 AND b1.n1 = 'B' AND b1.n2 = a2.n2
LEFT JOIN sys.dm_db_index_usage_stats y1 ON y1.database_id = DB_ID() AND y1.object_id = OBJECT_ID(a2.[name])
LEFT JOIN sys.dm_db_index_usage_stats y2 ON y2.database_id = DB_ID() AND y2.object_id = OBJECT_ID(b2.[name])
WHERE a2.cd = 2 AND a2.n1 = 'A' ORDER BY a2.[name]
GO
-- PRINT CONCAT('--',CONVERT(char(23),GETDATE(),121),', ',@Tabl,@sp,', ',STR(@Card,6),', ',STR(@Rg,6),', ',@Rw)
-- verify memory
/*
*/
/*
SELECT 'xx' a, statement_text, execution_count, total_worker_time, total_elapsed_time, tphys_reads, tlog_reads, total_rows, start_off, end_off,  av_w, creation_time, last_execution_time 
--into dbo.stat20221209a
FROM dbo.veqs WHERE  total_worker_time > 100000 AND execution_count >= 30  --AND start_off BETWEEN 200 AND 250  --
ORDER BY last_execution_time 

exec sp_spaceused2 @objname='stat%', @Ord=1
exec sp_rename 'dbo.stat20230328', 'stat20230328x'
--DROP TABLE IF EXISTS dbo.stat20221209a

exec sp_configure
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
*/
/*
exec sp_helpindex2 'AI1'
exec sp_rename 'AI1', 'AI2'
exec sp_rename 'BI1', 'BI2'
*/
GO
DBCC USEROPTIONS
GO
DBCC FREEPROCCACHE
GO
SET NOCOUNT ON
PRINT '-- Form1 Loop 1'
GO
DECLARE @I int, @R int SELECT @I = 1+681800*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A1  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I AND a.[SID] = 1 OPTION(MAXDOP 1)
GO 200000
DECLARE @I int, @R int SELECT @I = 1+681800*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A1  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 200000
DECLARE @I int, @R int SELECT @I = 1+454533*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A1A a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 200000
DECLARE @I int, @R int SELECT @I = 1+340900*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A2  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 180000
DECLARE @I int, @R int SELECT @I = 1+227266*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A2A a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 160000
DECLARE @I int, @R int SELECT @I = 1+170450*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A3  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 150000
DECLARE @I int, @R int SELECT @I = 1+113633*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A3A a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 135000
DECLARE @I int, @R int SELECT @I = 1+85225*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A4  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 120000
DECLARE @I int, @R int SELECT @I = 1+56816*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A4A a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 100000
DECLARE @I int, @R int SELECT @I = 1+42612*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A5  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 80000
DECLARE @I int, @R int SELECT @I = 1+28408*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A5A a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 60000
DECLARE @I int, @R int SELECT @I = 1+21306*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A6  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 50000
DECLARE @I int, @R int SELECT @I = 1+14204*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A6A a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 35000
DECLARE @I int, @R int SELECT @I = 1+10653*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A7  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 25000
DECLARE @I int, @R int SELECT @I = 1+7102*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A7A a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 20000
DECLARE @I int, @R int SELECT @I = 1+5326*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 15000
DECLARE @I int, @R int SELECT @I = 1+4261*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8B a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 13000
DECLARE @I int, @R int SELECT @I = 1+4058*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8C a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 12000
DECLARE @I int, @R int SELECT @I = 1+3874*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8D a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 11000
DECLARE @I int, @R int SELECT @I = 1+3551*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8A a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 10000
DECLARE @I int, @R int SELECT @I = 1+2663*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A9  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 7500
DECLARE @I int, @R int SELECT @I = 1+1775*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A9A a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 6000
DECLARE @I int, @R int SELECT @I = 1+1331*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AA  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 4000
DECLARE @I int, @R int SELECT @I = 1+887*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AA1 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 3000
DECLARE @I int, @R int SELECT @I = 1+665*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AB  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1850
DECLARE @I int, @R int SELECT @I = 1+443*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AB1 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1500
DECLARE @I int, @R int SELECT @I = 1+332*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AC  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1000
DECLARE @I int, @R int SELECT @I = 1+266*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AC1 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 800
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 500
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD1 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 480
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD2 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 440
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD5 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 440
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD6 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 440
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD8 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 430
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 420
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE1 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 400
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE2 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 390
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE3 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 380
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE4 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 320
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE5 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 280
DECLARE @I int, @R int SELECT @I = 1+404*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AF  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 230
DECLARE @I int, @R int SELECT @I = 1+269*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AF1 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 150
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AG  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 120
DECLARE @I int, @R int SELECT @I = 1+134*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AG1 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 80
DECLARE @I int, @R int SELECT @I = 1+101*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 60
DECLARE @I int, @R int SELECT @I = 1+67*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH1 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 45
DECLARE @I int, @R int SELECT @I = 1+57*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH2 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 40
DECLARE @I int, @R int SELECT @I = 1+50*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH4 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 37
DECLARE @I int, @R int SELECT @I = 1+50*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH5 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 36
DECLARE @I int, @R int SELECT @I = 1+50*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 35
DECLARE @I int, @R int SELECT @I = 1+40*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI1 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 33
DECLARE @I int, @R int SELECT @I = 1+33*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI2 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 32
DECLARE @I int, @R int SELECT @I = 1+28*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI3 a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 31
DECLARE @I int, @R int SELECT @I = 1+25*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AJ  a INNER LOOP JOIN dbo.A b ON b.AID = a.AID WHERE a.GID = @I OPTION(MAXDOP 1)
GO 30

GO
-- 1st stats SELECT INTO
DECLARE @s nvarchar(4000), @dt char(8) = CONVERT(char(8),GETDATE(),112)
SELECT @s = CONCAT('DROP TABLE IF EXISTS dbo.stat',@dt)
PRINT @s
exec sp_executesql @s
SELECT @s = CONCAT('SELECT CONVERT(varchar(20),''l1'') code, statement_text, execution_count, total_worker_time, total_elapsed_time, tphys_reads, tlog_reads, total_rows, start_off, end_off,  av_w, creation_time, last_execution_time 
INTO dbo.stat',@dt,'
FROM dbo.veqs WHERE  total_worker_time > 100000 AND execution_count >= 30 
ORDER BY last_execution_time')
PRINT @s
exec sp_executesql @s
SELECT @s = CONCAT('SELECT * FROM dbo.stat',@dt,' WHERE code =''l1'' ORDER BY last_execution_time ')
PRINT @s
exec sp_executesql @s
GO
/*
*/
GO
DBCC FREEPROCCACHE
GO
SET NOCOUNT ON
PRINT '-- Form1 Loop 2'
GO
DECLARE @I int, @R int SELECT @I = 1+681800*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A1  a INNER LOOP JOIN dbo.B1  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I AND a.[SID] = 1 OPTION(MAXDOP 1)
GO 200000
DECLARE @I int, @R int SELECT @I = 1+681800*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A1  a INNER LOOP JOIN dbo.B1  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 200000
DECLARE @I int, @R int SELECT @I = 1+454533*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A1A a INNER LOOP JOIN dbo.B1A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 200000
DECLARE @I int, @R int SELECT @I = 1+340900*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A2  a INNER LOOP JOIN dbo.B2  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 200000
DECLARE @I int, @R int SELECT @I = 1+227266*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A2A a INNER LOOP JOIN dbo.B2A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 200000
DECLARE @I int, @R int SELECT @I = 1+170450*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A3  a INNER LOOP JOIN dbo.B3  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 200000
DECLARE @I int, @R int SELECT @I = 1+113633*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A3A a INNER LOOP JOIN dbo.B3A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 180000
DECLARE @I int, @R int SELECT @I = 1+85225*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A4  a INNER LOOP JOIN dbo.B4  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 160000
DECLARE @I int, @R int SELECT @I = 1+56816*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A4A a INNER LOOP JOIN dbo.B4A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 130000
DECLARE @I int, @R int SELECT @I = 1+42612*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A5  a INNER LOOP JOIN dbo.B5  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 100000
DECLARE @I int, @R int SELECT @I = 1+28408*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A5A a INNER LOOP JOIN dbo.B5A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 80000
DECLARE @I int, @R int SELECT @I = 1+21306*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A6  a INNER LOOP JOIN dbo.B6  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 65000
DECLARE @I int, @R int SELECT @I = 1+14204*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A6A a INNER LOOP JOIN dbo.B6A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 50000
DECLARE @I int, @R int SELECT @I = 1+10653*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A7  a INNER LOOP JOIN dbo.B7  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 35000
DECLARE @I int, @R int SELECT @I = 1+7102*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A7A a INNER LOOP JOIN dbo.B7A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 27000
DECLARE @I int, @R int SELECT @I = 1+5326*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8  a INNER LOOP JOIN dbo.B8  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 20000
DECLARE @I int, @R int SELECT @I = 1+4261*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8B a INNER LOOP JOIN dbo.B8B b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 17000
DECLARE @I int, @R int SELECT @I = 1+4058*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8C a INNER LOOP JOIN dbo.B8C b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 16000
DECLARE @I int, @R int SELECT @I = 1+3874*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8D a INNER LOOP JOIN dbo.B8D b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 15000
DECLARE @I int, @R int SELECT @I = 1+3551*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8A a INNER LOOP JOIN dbo.B8A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 14000
DECLARE @I int, @R int SELECT @I = 1+2663*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A9  a INNER LOOP JOIN dbo.B9  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 10000
DECLARE @I int, @R int SELECT @I = 1+1775*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A9A a INNER LOOP JOIN dbo.B9A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 7000
DECLARE @I int, @R int SELECT @I = 1+1331*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AA  a INNER LOOP JOIN dbo.BA  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 5000
DECLARE @I int, @R int SELECT @I = 1+887*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AA1 a INNER LOOP JOIN dbo.BA1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 3500
DECLARE @I int, @R int SELECT @I = 1+665*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AB  a INNER LOOP JOIN dbo.BB  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 2500
DECLARE @I int, @R int SELECT @I = 1+443*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AB1 a INNER LOOP JOIN dbo.BB1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1900
DECLARE @I int, @R int SELECT @I = 1+332*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AC  a INNER LOOP JOIN dbo.BC  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1300
DECLARE @I int, @R int SELECT @I = 1+266*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AC1 a INNER LOOP JOIN dbo.BC1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1000
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD  a INNER LOOP JOIN dbo.BD  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 650
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD1 a INNER LOOP JOIN dbo.BD1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 600
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD2 a INNER LOOP JOIN dbo.BD2 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 595
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD5 a INNER LOOP JOIN dbo.BD5 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 585
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD6 a INNER LOOP JOIN dbo.BD6 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 590
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD8 a INNER LOOP JOIN dbo.BD8 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 570
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE  a INNER LOOP JOIN dbo.BE  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 550
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE1 a INNER LOOP JOIN dbo.BE1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 520
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE2 a INNER LOOP JOIN dbo.BE2 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 510
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE3 a INNER LOOP JOIN dbo.BE3 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 500
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE4 a INNER LOOP JOIN dbo.BE4 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 420
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE5 a INNER LOOP JOIN dbo.BE5 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 350
DECLARE @I int, @R int SELECT @I = 1+404*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AF  a INNER LOOP JOIN dbo.BF  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 320
DECLARE @I int, @R int SELECT @I = 1+269*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AF1 a INNER LOOP JOIN dbo.BF1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 210
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AG  a INNER LOOP JOIN dbo.BG  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 160
DECLARE @I int, @R int SELECT @I = 1+134*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AG1 a INNER LOOP JOIN dbo.BG1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 110
DECLARE @I int, @R int SELECT @I = 1+101*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH  a INNER LOOP JOIN dbo.BH  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 80
DECLARE @I int, @R int SELECT @I = 1+67*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH1 a INNER LOOP JOIN dbo.BH1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 55
DECLARE @I int, @R int SELECT @I = 1+57*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH2 a INNER LOOP JOIN dbo.BH2 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 50
DECLARE @I int, @R int SELECT @I = 1+50*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH4 a INNER LOOP JOIN dbo.BH4 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 40
DECLARE @I int, @R int SELECT @I = 1+50*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH5 a INNER LOOP JOIN dbo.BH5 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 35
DECLARE @I int, @R int SELECT @I = 1+50*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI  a INNER LOOP JOIN dbo.BI  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 40
DECLARE @I int, @R int SELECT @I = 1+40*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI1 a INNER LOOP JOIN dbo.BI1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 35
DECLARE @I int, @R int SELECT @I = 1+33*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI2 a INNER LOOP JOIN dbo.BI2 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 32
DECLARE @I int, @R int SELECT @I = 1+28*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI3 a INNER LOOP JOIN dbo.BI3 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 31
DECLARE @I int, @R int SELECT @I = 1+25*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AJ  a INNER LOOP JOIN dbo.BJ  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 30

GO
DECLARE @s nvarchar(4000), @dt char(8) = CONVERT(char(8),GETDATE(),112)
SELECT @s = CONCAT('INSERT dbo.stat',@dt,'
SELECT ''l2'' code, statement_text, execution_count, total_worker_time, total_elapsed_time, tphys_reads, tlog_reads, total_rows, start_off, end_off,  av_w, creation_time, last_execution_time 
FROM dbo.veqs WHERE  total_worker_time > 100000 AND execution_count >= 30 
ORDER BY last_execution_time')
PRINT @s
exec sp_executesql @s
SELECT @s = CONCAT('SELECT * FROM dbo.stat',@dt,' WHERE code =''l2'' ORDER BY last_execution_time ')
PRINT @s
exec sp_executesql @s
GO
/*
*/
GO
DBCC FREEPROCCACHE
GO
SET NOCOUNT ON
PRINT '-- Form1 Merge'
GO
-- Form1 Merge
DECLARE @I int, @R int SELECT @I = 1+681800*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A1  a INNER MERGE JOIN dbo.B1  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I AND a.[SID] = 1 OPTION(MAXDOP 1)
GO 200000
DECLARE @I int, @R int SELECT @I = 1+681800*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A1  a INNER MERGE JOIN dbo.B1  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 200000
DECLARE @I int, @R int SELECT @I = 1+454533*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A1A a INNER MERGE JOIN dbo.B1A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 200000
DECLARE @I int, @R int SELECT @I = 1+340900*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A2  a INNER MERGE JOIN dbo.B2  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 200000
DECLARE @I int, @R int SELECT @I = 1+227266*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A2A a INNER MERGE JOIN dbo.B2A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 200000
DECLARE @I int, @R int SELECT @I = 1+170450*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A3  a INNER MERGE JOIN dbo.B3  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 200000
DECLARE @I int, @R int SELECT @I = 1+113633*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A3A a INNER MERGE JOIN dbo.B3A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 200000
DECLARE @I int, @R int SELECT @I = 1+85225*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A4  a INNER MERGE JOIN dbo.B4  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 200000
DECLARE @I int, @R int SELECT @I = 1+56816*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A4A a INNER MERGE JOIN dbo.B4A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 200000
DECLARE @I int, @R int SELECT @I = 1+42612*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A5  a INNER MERGE JOIN dbo.B5  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 190000
DECLARE @I int, @R int SELECT @I = 1+28408*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A5A a INNER MERGE JOIN dbo.B5A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 160000
DECLARE @I int, @R int SELECT @I = 1+21306*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A6  a INNER MERGE JOIN dbo.B6  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 140000
DECLARE @I int, @R int SELECT @I = 1+14204*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A6A a INNER MERGE JOIN dbo.B6A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 110000
DECLARE @I int, @R int SELECT @I = 1+10653*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A7  a INNER MERGE JOIN dbo.B7  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 90000
DECLARE @I int, @R int SELECT @I = 1+7102*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A7A a INNER MERGE JOIN dbo.B7A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 70000
DECLARE @I int, @R int SELECT @I = 1+5326*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8  a INNER MERGE JOIN dbo.B8  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 50000
DECLARE @I int, @R int SELECT @I = 1+4261*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8B a INNER MERGE JOIN dbo.B8B b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 46000
DECLARE @I int, @R int SELECT @I = 1+4058*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8C a INNER MERGE JOIN dbo.B8C b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 44000
DECLARE @I int, @R int SELECT @I = 1+3874*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8D a INNER MERGE JOIN dbo.B8D b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 42000
DECLARE @I int, @R int SELECT @I = 1+3551*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8A a INNER MERGE JOIN dbo.B8A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 40000
DECLARE @I int, @R int SELECT @I = 1+2663*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A9  a INNER MERGE JOIN dbo.B9  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 30000
DECLARE @I int, @R int SELECT @I = 1+1775*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A9A a INNER MERGE JOIN dbo.B9A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 23000
DECLARE @I int, @R int SELECT @I = 1+1331*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AA  a INNER MERGE JOIN dbo.BA  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 17000
DECLARE @I int, @R int SELECT @I = 1+887*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AA1 a INNER MERGE JOIN dbo.BA1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 13000
DECLARE @I int, @R int SELECT @I = 1+665*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AB  a INNER MERGE JOIN dbo.BB  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 8000
DECLARE @I int, @R int SELECT @I = 1+443*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AB1 a INNER MERGE JOIN dbo.BB1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 6500
DECLARE @I int, @R int SELECT @I = 1+332*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AC  a INNER MERGE JOIN dbo.BC  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 4500
DECLARE @I int, @R int SELECT @I = 1+266*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AC1 a INNER MERGE JOIN dbo.BC1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 3500
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD  a INNER MERGE JOIN dbo.BD  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 2100
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD1 a INNER MERGE JOIN dbo.BD1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 2050
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD2 a INNER MERGE JOIN dbo.BD2 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 2030
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD5 a INNER MERGE JOIN dbo.BD5 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 2000
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD6 a INNER MERGE JOIN dbo.BD6 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 2020
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD8 a INNER MERGE JOIN dbo.BD8 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 2010
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE  a INNER MERGE JOIN dbo.BE  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 2000
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE1 a INNER MERGE JOIN dbo.BE1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1900
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE2 a INNER MERGE JOIN dbo.BE2 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1800
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE3 a INNER MERGE JOIN dbo.BE3 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1700
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE4 a INNER MERGE JOIN dbo.BE4 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1600
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE5 a INNER MERGE JOIN dbo.BE5 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1300
DECLARE @I int, @R int SELECT @I = 1+404*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AF  a INNER MERGE JOIN dbo.BF  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1200
DECLARE @I int, @R int SELECT @I = 1+269*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AF1 a INNER MERGE JOIN dbo.BF1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 700
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AG  a INNER MERGE JOIN dbo.BG  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 600
DECLARE @I int, @R int SELECT @I = 1+134*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AG1 a INNER MERGE JOIN dbo.BG1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 400
DECLARE @I int, @R int SELECT @I = 1+101*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH  a INNER MERGE JOIN dbo.BH  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 300
DECLARE @I int, @R int SELECT @I = 1+67*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH1 a INNER MERGE JOIN dbo.BH1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 200
DECLARE @I int, @R int SELECT @I = 1+57*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH2 a INNER MERGE JOIN dbo.BH2 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 180
DECLARE @I int, @R int SELECT @I = 1+50*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH4 a INNER MERGE JOIN dbo.BH4 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 150
DECLARE @I int, @R int SELECT @I = 1+50*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH5 a INNER MERGE JOIN dbo.BH5 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 140
DECLARE @I int, @R int SELECT @I = 1+50*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI  a INNER MERGE JOIN dbo.BI  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 145
DECLARE @I int, @R int SELECT @I = 1+40*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI1 a INNER MERGE JOIN dbo.BI1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 120
DECLARE @I int, @R int SELECT @I = 1+33*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI2 a INNER MERGE JOIN dbo.BI2 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 110
DECLARE @I int, @R int SELECT @I = 1+28*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI3 a INNER MERGE JOIN dbo.BI3 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 105
DECLARE @I int, @R int SELECT @I = 1+25*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AJ  a INNER MERGE JOIN dbo.BJ  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 100

GO
DECLARE @s nvarchar(4000), @dt char(8) = CONVERT(char(8),GETDATE(),112)
SELECT @s = CONCAT('INSERT dbo.stat',@dt,'
SELECT ''me'' code, statement_text, execution_count, total_worker_time, total_elapsed_time, tphys_reads, tlog_reads, total_rows, start_off, end_off,  av_w, creation_time, last_execution_time 
FROM dbo.veqs WHERE  total_worker_time > 100000 AND execution_count >= 30 
ORDER BY last_execution_time')
PRINT @s
exec sp_executesql @s
SELECT @s = CONCAT('SELECT * FROM dbo.stat',@dt,' WHERE code =''me'' ORDER BY last_execution_time ')
PRINT @s
exec sp_executesql @s
GO
/*
SELECT * FROM dbo.zTest
*/
GO
DBCC FREEPROCCACHE
GO
SET NOCOUNT ON
PRINT '-- Form1 Hash'
GO
DECLARE @I int, @R int SELECT @I = 1+681800*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A1  a INNER HASH JOIN dbo.B1  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I AND a.[SID] = 1 OPTION(MAXDOP 1)
GO 35000
DECLARE @I int, @R int SELECT @I = 1+681800*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A1  a INNER HASH JOIN dbo.B1  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 30000
DECLARE @I int, @R int SELECT @I = 1+454533*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A1A a INNER HASH JOIN dbo.B1A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 29000
DECLARE @I int, @R int SELECT @I = 1+340900*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A2  a INNER HASH JOIN dbo.B2  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 28000
DECLARE @I int, @R int SELECT @I = 1+227266*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A2A a INNER HASH JOIN dbo.B2A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 27500
DECLARE @I int, @R int SELECT @I = 1+170450*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A3  a INNER HASH JOIN dbo.B3  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 27000
DECLARE @I int, @R int SELECT @I = 1+113633*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A3A a INNER HASH JOIN dbo.B3A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 26500
DECLARE @I int, @R int SELECT @I = 1+85225*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A4  a INNER HASH JOIN dbo.B4  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 26000
DECLARE @I int, @R int SELECT @I = 1+56816*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A4A a INNER HASH JOIN dbo.B4A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 25500
DECLARE @I int, @R int SELECT @I = 1+42612*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A5  a INNER HASH JOIN dbo.B5  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 25000
DECLARE @I int, @R int SELECT @I = 1+28408*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A5A a INNER HASH JOIN dbo.B5A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 24500
DECLARE @I int, @R int SELECT @I = 1+21306*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A6  a INNER HASH JOIN dbo.B6  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 24000
DECLARE @I int, @R int SELECT @I = 1+14204*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A6A a INNER HASH JOIN dbo.B6A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 22000
DECLARE @I int, @R int SELECT @I = 1+10653*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A7  a INNER HASH JOIN dbo.B7  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 20000
DECLARE @I int, @R int SELECT @I = 1+7102*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A7A a INNER HASH JOIN dbo.B7A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 18000
DECLARE @I int, @R int SELECT @I = 1+5326*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8  a INNER HASH JOIN dbo.B8  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 16000
DECLARE @I int, @R int SELECT @I = 1+4261*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8B a INNER HASH JOIN dbo.B8B b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 15500
DECLARE @I int, @R int SELECT @I = 1+4058*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8C a INNER HASH JOIN dbo.B8C b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 15000
DECLARE @I int, @R int SELECT @I = 1+3874*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8D a INNER HASH JOIN dbo.B8D b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 14500
DECLARE @I int, @R int SELECT @I = 1+3551*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8A a INNER HASH JOIN dbo.B8A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 14000
DECLARE @I int, @R int SELECT @I = 1+2663*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A9  a INNER HASH JOIN dbo.B9  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 12000
DECLARE @I int, @R int SELECT @I = 1+1775*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A9A a INNER HASH JOIN dbo.B9A b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 10000
DECLARE @I int, @R int SELECT @I = 1+1331*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AA  a INNER HASH JOIN dbo.BA  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 8000
DECLARE @I int, @R int SELECT @I = 1+887*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AA1 a INNER HASH JOIN dbo.BA1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 6500
DECLARE @I int, @R int SELECT @I = 1+665*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AB  a INNER HASH JOIN dbo.BB  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 4500
DECLARE @I int, @R int SELECT @I = 1+443*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AB1 a INNER HASH JOIN dbo.BB1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 3500
DECLARE @I int, @R int SELECT @I = 1+332*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AC  a INNER HASH JOIN dbo.BC  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 2500
DECLARE @I int, @R int SELECT @I = 1+266*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AC1 a INNER HASH JOIN dbo.BC1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 2000
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD  a INNER HASH JOIN dbo.BD  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1260
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD1 a INNER HASH JOIN dbo.BD1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1250
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD2 a INNER HASH JOIN dbo.BD2 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1230
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD5 a INNER HASH JOIN dbo.BD5 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1200
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD6 a INNER HASH JOIN dbo.BD6 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1220
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD8 a INNER HASH JOIN dbo.BD8 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1200
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE  a INNER HASH JOIN dbo.BE  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1120
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE1 a INNER HASH JOIN dbo.BE1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1100
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE2 a INNER HASH JOIN dbo.BE2 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1020
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE3 a INNER HASH JOIN dbo.BE3 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1000
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE4 a INNER HASH JOIN dbo.BE4 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 850
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE5 a INNER HASH JOIN dbo.BE5 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 700
DECLARE @I int, @R int SELECT @I = 1+404*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AF  a INNER HASH JOIN dbo.BF  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 600
DECLARE @I int, @R int SELECT @I = 1+269*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AF1 a INNER HASH JOIN dbo.BF1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 420
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AG  a INNER HASH JOIN dbo.BG  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 320
DECLARE @I int, @R int SELECT @I = 1+134*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AG1 a INNER HASH JOIN dbo.BG1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 220
DECLARE @I int, @R int SELECT @I = 1+101*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH  a INNER HASH JOIN dbo.BH  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 160
DECLARE @I int, @R int SELECT @I = 1+67*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH1 a INNER HASH JOIN dbo.BH1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 110
DECLARE @I int, @R int SELECT @I = 1+57*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH2 a INNER HASH JOIN dbo.BH2 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 90
DECLARE @I int, @R int SELECT @I = 1+50*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH4 a INNER HASH JOIN dbo.BH4 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 80
DECLARE @I int, @R int SELECT @I = 1+50*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH5 a INNER HASH JOIN dbo.BH5 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 75

DECLARE @I int, @R int SELECT @I = 1+50*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI  a INNER HASH JOIN dbo.BI  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1, USE HINT('DISALLOW_BATCH_MODE'))
GO 80
DECLARE @I int, @R int SELECT @I = 1+40*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI1 a INNER HASH JOIN dbo.BI1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1, USE HINT('DISALLOW_BATCH_MODE'))
GO 55
DECLARE @I int, @R int SELECT @I = 1+33*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI2 a INNER HASH JOIN dbo.BI2 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1, USE HINT('DISALLOW_BATCH_MODE'))
GO 50
DECLARE @I int, @R int SELECT @I = 1+28*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI3 a INNER HASH JOIN dbo.BI3 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1, USE HINT('DISALLOW_BATCH_MODE'))
GO 42
DECLARE @I int, @R int SELECT @I = 1+25*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AJ  a INNER HASH JOIN dbo.BJ  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1, USE HINT('DISALLOW_BATCH_MODE'))
GO 40

DECLARE @I int, @R int SELECT @I = 1+50*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI  a INNER HASH JOIN dbo.BI  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 160
DECLARE @I int, @R int SELECT @I = 1+40*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI1 a INNER HASH JOIN dbo.BI1 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 110
DECLARE @I int, @R int SELECT @I = 1+33*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI2 a INNER HASH JOIN dbo.BI2 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 100
DECLARE @I int, @R int SELECT @I = 1+28*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI3 a INNER HASH JOIN dbo.BI3 b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 84
DECLARE @I int, @R int SELECT @I = 1+25*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AJ  a INNER HASH JOIN dbo.BJ  b ON b.GID = a.GID AND b.[SID] = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 80
GO
DECLARE @s nvarchar(4000), @dt char(8) = CONVERT(char(8),GETDATE(),112)
SELECT @s = CONCAT('INSERT dbo.stat',@dt,'
SELECT ''ha'' code, statement_text, execution_count, total_worker_time, total_elapsed_time, tphys_reads, tlog_reads, total_rows, start_off, end_off,  av_w, creation_time, last_execution_time 
FROM dbo.veqs WHERE  total_worker_time > 100000 AND execution_count >= 30 
ORDER BY last_execution_time')
PRINT @s
exec sp_executesql @s

SELECT @s = CONCAT('SELECT * FROM dbo.stat',@dt,' WHERE code =''ha'' ORDER BY last_execution_time ')
PRINT @s
exec sp_executesql @s
GO
/*
*/
GO
DBCC FREEPROCCACHE
GO
SET NOCOUNT ON
PRINT '-- Form1 Sort M'
GO
DECLARE @I int, @R int SELECT @I = 1+681800*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A1  a INNER MERGE JOIN dbo.B1  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 130000
DECLARE @I int, @R int SELECT @I = 1+454533*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A1A a INNER MERGE JOIN dbo.B1A b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 127000
DECLARE @I int, @R int SELECT @I = 1+340900*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A2  a INNER MERGE JOIN dbo.B2  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 125000
DECLARE @I int, @R int SELECT @I = 1+227266*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A2A a INNER MERGE JOIN dbo.B2A b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 120000
DECLARE @I int, @R int SELECT @I = 1+170450*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A3  a INNER MERGE JOIN dbo.B3  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 115000
DECLARE @I int, @R int SELECT @I = 1+113633*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A3A a INNER MERGE JOIN dbo.B3A b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 112000
DECLARE @I int, @R int SELECT @I = 1+85225*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A4  a INNER MERGE JOIN dbo.B4  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 110000
DECLARE @I int, @R int SELECT @I = 1+56816*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A4A a INNER MERGE JOIN dbo.B4A b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 95000
DECLARE @I int, @R int SELECT @I = 1+42612*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A5  a INNER MERGE JOIN dbo.B5  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 85000
DECLARE @I int, @R int SELECT @I = 1+28408*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A5A a INNER MERGE JOIN dbo.B5A b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 80000
DECLARE @I int, @R int SELECT @I = 1+21306*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A6  a INNER MERGE JOIN dbo.B6  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 70000
DECLARE @I int, @R int SELECT @I = 1+14204*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A6A a INNER MERGE JOIN dbo.B6A b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 60000
DECLARE @I int, @R int SELECT @I = 1+10653*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A7  a INNER MERGE JOIN dbo.B7  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 55000
DECLARE @I int, @R int SELECT @I = 1+7102*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A7A a INNER MERGE JOIN dbo.B7A b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 45000
DECLARE @I int, @R int SELECT @I = 1+5326*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8  a INNER MERGE JOIN dbo.B8  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 35000
DECLARE @I int, @R int SELECT @I = 1+4261*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8B a INNER MERGE JOIN dbo.B8B b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 30000
DECLARE @I int, @R int SELECT @I = 1+4058*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8C a INNER MERGE JOIN dbo.B8C b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 29000
DECLARE @I int, @R int SELECT @I = 1+3874*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8D a INNER MERGE JOIN dbo.B8D b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 28000
DECLARE @I int, @R int SELECT @I = 1+3551*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A8A a INNER MERGE JOIN dbo.B8A b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 27000
DECLARE @I int, @R int SELECT @I = 1+2663*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A9  a INNER MERGE JOIN dbo.B9  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 20000
DECLARE @I int, @R int SELECT @I = 1+1775*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.A9A a INNER MERGE JOIN dbo.B9A b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 15000
DECLARE @I int, @R int SELECT @I = 1+1331*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AA  a INNER MERGE JOIN dbo.BA  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 11000
DECLARE @I int, @R int SELECT @I = 1+887*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AA1 a INNER MERGE JOIN dbo.BA1 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 8500
DECLARE @I int, @R int SELECT @I = 1+665*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AB  a INNER MERGE JOIN dbo.BB  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 6000
DECLARE @I int, @R int SELECT @I = 1+443*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AB1 a INNER MERGE JOIN dbo.BB1 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 4500
DECLARE @I int, @R int SELECT @I = 1+332*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AC  a INNER MERGE JOIN dbo.BC  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 3200
DECLARE @I int, @R int SELECT @I = 1+266*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AC1 a INNER MERGE JOIN dbo.BC1 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 2500
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD  a INNER MERGE JOIN dbo.BD  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1500
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD1 a INNER MERGE JOIN dbo.BD1 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1470
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD2 a INNER MERGE JOIN dbo.BD2 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1450
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD5 a INNER MERGE JOIN dbo.BD5 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1410
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD6 a INNER MERGE JOIN dbo.BD6 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1420
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AD8 a INNER MERGE JOIN dbo.BD8 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1380
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE  a INNER MERGE JOIN dbo.BE  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1320
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE1 a INNER MERGE JOIN dbo.BE1 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1300
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE2 a INNER MERGE JOIN dbo.BE2 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1240
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE3 a INNER MERGE JOIN dbo.BE3 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1200
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE4 a INNER MERGE JOIN dbo.BE4 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 1000
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AE5 a INNER MERGE JOIN dbo.BE5 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 900
DECLARE @I int, @R int SELECT @I = 1+404*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AF  a INNER MERGE JOIN dbo.BF  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 800
DECLARE @I int, @R int SELECT @I = 1+269*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AF1 a INNER MERGE JOIN dbo.BF1 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 500
DECLARE @I int, @R int SELECT @I = 1+202*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AG  a INNER MERGE JOIN dbo.BG  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 400
DECLARE @I int, @R int SELECT @I = 1+134*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AG1 a INNER MERGE JOIN dbo.BG1 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 260
DECLARE @I int, @R int SELECT @I = 1+101*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH  a INNER MERGE JOIN dbo.BH  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 200
DECLARE @I int, @R int SELECT @I = 1+67*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH1 a INNER MERGE JOIN dbo.BH1 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 140
DECLARE @I int, @R int SELECT @I = 1+57*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH2 a INNER MERGE JOIN dbo.BH2 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 120
DECLARE @I int, @R int SELECT @I = 1+50*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH4 a INNER MERGE JOIN dbo.BH4 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 105
DECLARE @I int, @R int SELECT @I = 1+50*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AH5 a INNER MERGE JOIN dbo.BH5 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 95

DECLARE @I int, @R int SELECT @I = 1+50*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI  a INNER MERGE JOIN dbo.BI  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1, USE HINT('DISALLOW_BATCH_MODE'))
GO 100
DECLARE @I int, @R int SELECT @I = 1+40*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI1 a INNER MERGE JOIN dbo.BI1 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1, USE HINT('DISALLOW_BATCH_MODE'))
GO 80
DECLARE @I int, @R int SELECT @I = 1+33*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI2 a INNER MERGE JOIN dbo.BI2 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1, USE HINT('DISALLOW_BATCH_MODE'))
GO 70
DECLARE @I int, @R int SELECT @I = 1+28*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI3 a INNER MERGE JOIN dbo.BI3 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1, USE HINT('DISALLOW_BATCH_MODE'))
GO 60
DECLARE @I int, @R int SELECT @I = 1+25*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AJ  a INNER MERGE JOIN dbo.BJ  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1, USE HINT('DISALLOW_BATCH_MODE'))
GO 50

DECLARE @I int, @R int SELECT @I = 1+50*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI  a INNER MERGE JOIN dbo.BI  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 200
DECLARE @I int, @R int SELECT @I = 1+40*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI1 a INNER MERGE JOIN dbo.BI1 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 160
DECLARE @I int, @R int SELECT @I = 1+33*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI2 a INNER MERGE JOIN dbo.BI2 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 140
DECLARE @I int, @R int SELECT @I = 1+28*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AI3 a INNER MERGE JOIN dbo.BI3 b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 120
DECLARE @I int, @R int SELECT @I = 1+25*RAND(CHECKSUM(NEWID())); SELECT @R=MAX(b.TI) FROM dbo.AJ  a INNER MERGE JOIN dbo.BJ  b ON b.GID = a.GID AND b.BID = a.[SID] WHERE a.GID = @I OPTION(MAXDOP 1)
GO 100
GO
DECLARE @s nvarchar(4000), @dt char(8) = CONVERT(char(8),GETDATE(),112)
SELECT @s = CONCAT('INSERT dbo.stat',@dt,'
SELECT ''sm'' code, statement_text, execution_count, total_worker_time, total_elapsed_time, tphys_reads, tlog_reads, total_rows, start_off, end_off,  av_w, creation_time, last_execution_time 
FROM dbo.veqs WHERE  total_worker_time > 100000 AND execution_count >= 30 
ORDER BY last_execution_time')
PRINT @s
exec sp_executesql @s

SELECT @s = CONCAT('SELECT * FROM dbo.stat',@dt,' WHERE code =''sm'' ORDER BY last_execution_time ')
PRINT @s
exec sp_executesql @s
GO

/*
SELECT CONVERT(varchar(20),'xx') code, statement_text, execution_count, total_worker_time, total_elapsed_time, tphys_reads, tlog_reads, total_rows, start_off, end_off,  av_w, creation_time, last_execution_time 
--INTO dbo.stat20221214x
FROM dbo.veqs WHERE  total_worker_time > 100000 AND execution_count >= 30 
ORDER BY last_execution_time

INSERT dbo.stat20221214x
SELECT CONVERT(varchar(20),'xz') code, statement_text, execution_count, total_worker_time, total_elapsed_time, tphys_reads, tlog_reads, total_rows, start_off, end_off,  av_w, creation_time, last_execution_time 
FROM dbo.veqs WHERE  total_worker_time > 100000 AND execution_count >= 30 
ORDER BY last_execution_time

INSERT dbo.stat20221221b
SELECT 'sm' code, statement_text, execution_count, total_worker_time, total_elapsed_time, tphys_reads, tlog_reads, total_rows, start_off, end_off,  av_w, creation_time, last_execution_time 
FROM dbo.veqs WHERE  total_worker_time > 100000 AND execution_count >= 30 
ORDER BY last_execution_time

SELECT * FROM dbo.stat20221221 ORDER BY last_execution_time

exec sp_rename 'dbo.stat20221221','stat20221221a'
exec sp_rename 'dbo.stat20221221','stat20221221b'

exec sp_rename 'dbo.stat20230328','stat20230326c'
exec sp_spaceused2 @objname='stat%', @Ord=1 

exec sp_rename 'dbo.stat20230326ax','stat20230326a'
*/

/*
exec sp_help 'stat20221213'

exec sp_spaceused2 @objname='stat%', @Ord=1
exec sp_spaceused2 @objname='A%', @Ord=1
*/



